apiVersion: v1
kind: Service
metadata:
  name: mywebsvr
spec:
  selector:
    app: mywebsvr
  type: ClusterIP
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080

